DROP TABLE IF EXISTS pokemon;

CREATE TABLE pokemon (
	No. INTEGER NOT NULL,
	Name VARCHAR(20) NOT NULL,
	HP INTEGER NOT NULL,
	Att INTEGER NOT NULL,
	Def INTEGER NOT NULL,
	S.Att INTEGER NOT NULL,
	S.Def INTEGER NOT NULL,
	Spd INTEGER NOT NULL,
	Type 1 VARCHAR(10) NOT NULL,
	Type 2 VARCHAR(10),
	Height NUMERIC(1) NOT NULL,
	Weight NUMERIC(1) NOT NULL,
	Ability 1 VARCHAR(20) NOT NULL,
	Ability 2 VARCHAR(20),
	Hidden Ability VARCHAR(20),
	Legendary VARCHAR(10) NOT NULL
	PRIMARY KEY (No.)
);
